server:
  port: 8081

spring: 
  application:
     name : course-service
     
  zipkin:
    enabled: true

  datasource: 
    url : jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    username : root
    password : root
  jpa: 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection: 
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true
    show-sql: true 
    hibernate:
      ddl-auto: update
      
#  config:
#    import: optional:configserver:http://localhost:8086
#
  profiles:
    active: prod    
    
    
# enables Spring Boot Actuator end points
management:
  endpoints:
    web:
      exposure:
        include: "*"        
     

      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka